package View.Admin;

import Controller.LoginController;
import View.Initial;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.Locale;

public class AdminOperation {
    public JPanel JPMain;
    private JButton JButtonLogout;
    private JLabel JLabelWelcomeAdmin;
    private JPanel JPHead;
    private JPanel JPButtons;
    private JButton JBUser;
    private JButton JBLog;
    private JButton bookManagementButton;
    private JButton JBBookRecord;
    private JButton JBReport;

    public AdminOperation(JFrame frame) {
        frame.setTitle("AdminOperation");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(800, 130);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        JLabelWelcomeAdmin.setText("Welcome, " + Initial.ID);


        JButtonLogout.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frame.setContentPane(new Initial(frame).JPMain);
            }
        });
        JBUser.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frame.setContentPane(new UserManagement(frame).JPMain);
            }
        });
        JBLog.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frame.setContentPane(new Log(frame).JPMain);
            }
        });
        bookManagementButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frame.setContentPane(new BookManagement(frame).JPMain);
            }
        });
        JBBookRecord.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frame.setContentPane(new BookRecord(frame).JPMain);
            }
        });
        JBReport.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frame.setContentPane(new AnalysisReport(frame).JPMain);
            }
        });
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        JPMain = new JPanel();
        JPMain.setLayout(new BorderLayout(0, 0));
        JPMain.setBackground(new Color(-11373958));
        Font JPMainFont = this.$$$getFont$$$("Arial Black", -1, 20, JPMain.getFont());
        if (JPMainFont != null) JPMain.setFont(JPMainFont);
        JPMain.setToolTipText("123");
        JPHead = new JPanel();
        JPHead.setLayout(new GridBagLayout());
        JPHead.setBackground(new Color(-7086643));
        JPMain.add(JPHead, BorderLayout.NORTH);
        JPHead.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-4473925)));
        JLabelWelcomeAdmin = new JLabel();
        Font JLabelWelcomeAdminFont = this.$$$getFont$$$("Arial Black", -1, 20, JLabelWelcomeAdmin.getFont());
        if (JLabelWelcomeAdminFont != null) JLabelWelcomeAdmin.setFont(JLabelWelcomeAdminFont);
        JLabelWelcomeAdmin.setForeground(new Color(-394759));
        JLabelWelcomeAdmin.setText("Welcome, Jay!");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 0, 5, 150);
        JPHead.add(JLabelWelcomeAdmin, gbc);
        JButtonLogout = new JButton();
        JButtonLogout.setEnabled(true);
        Font JButtonLogoutFont = this.$$$getFont$$$("Arial", -1, 12, JButtonLogout.getFont());
        if (JButtonLogoutFont != null) JButtonLogout.setFont(JButtonLogoutFont);
        JButtonLogout.setForeground(new Color(-9737365));
        JButtonLogout.setHorizontalTextPosition(11);
        JButtonLogout.setText("Logout");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 0, 5, 0);
        JPHead.add(JButtonLogout, gbc);
        JPButtons = new JPanel();
        JPButtons.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 10));
        JPButtons.setBackground(new Color(-6828067));
        JPButtons.setForeground(new Color(-6828067));
        JPMain.add(JPButtons, BorderLayout.CENTER);
        JPButtons.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        JBUser = new JButton();
        JBUser.setActionCommand("");
        JBUser.setAutoscrolls(false);
        JBUser.setBackground(new Color(-9017150));
        JBUser.setEnabled(true);
        JBUser.setForeground(new Color(-1907998));
        JBUser.setText("User Management");
        JPButtons.add(JBUser);
        JBLog = new JButton();
        JBLog.setBackground(new Color(-15022631));
        JBLog.setForeground(new Color(-789517));
        JBLog.setText("Admin Log System");
        JPButtons.add(JBLog);
        bookManagementButton = new JButton();
        bookManagementButton.setActionCommand("JBBook");
        bookManagementButton.setBackground(new Color(-13345850));
        bookManagementButton.setForeground(new Color(-789517));
        bookManagementButton.setText("Book Management");
        JPButtons.add(bookManagementButton);
        JBBookRecord = new JButton();
        JBBookRecord.setActionCommand("JBBook");
        JBBookRecord.setBackground(new Color(-6656570));
        JBBookRecord.setForeground(new Color(-789517));
        JBBookRecord.setText("Book Record");
        JPButtons.add(JBBookRecord);
        JBReport = new JButton();
        JBReport.setActionCommand("JBBook");
        JBReport.setBackground(new Color(-6626143));
        JBReport.setForeground(new Color(-789517));
        JBReport.setText("Analysis Report");
        JPButtons.add(JBReport);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return JPMain;
    }

}

