package View.Admin;

import Controller.OracleDB;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.*;
import Controller.logController;
import View.Initial;
import View.Oracle_Login;

public class Log {
    private JTable JTableLog;
    JPanel JPMain;
    private JPanel JPTable;
    private JButton JBBack;
    private JPanel JPButton2;

    public Log(JFrame frame) {
        String[] titles = {"Admin Account", "Operation Detail", "Operation Time"};
        String[][] data = {};
        String id = Initial.ID;
        DefaultTableModel model = new DefaultTableModel(data, titles);
        JTableLog.setModel(model);
        JScrollPane s = new JScrollPane(JTableLog);
        JPMain.add(s, BorderLayout.NORTH);
        OracleDB oracleDB = Oracle_Login.oracleDB;
        try {
            ResultSet res1 = logController.rgetall(Initial.ID, oracleDB);
            ResultSet res2 = logController.ogetall(Initial.ID, oracleDB);
            if (!res1.next()) {
                System.out.print("no");
            } else {
                do {
                    Vector<String> row = new Vector();
                    row.add(id);
                    String record = "user " + res1.getString("LOGINID_USER") + "'s account has been " + res1.getString("OPERATIONTYPE");
                    row.add(record);
                    row.add(res1.getString("REACTIVATIONTIME"));
                    model.addRow(row);
                } while (res1.next());
            }
            if (!res2.next()) {
                System.out.print("yes");
            } else {
                do {
                    Vector<String> row = new Vector();
                    row.add(id);
                    String record = "Book " + res2.getString("BOOKID") + " has been " + res2.getString("OPERATIONTYPE");
                    row.add(record);
                    row.add(res2.getString("OPERATIONTIME"));
                    model.addRow(row);
                } while (res2.next());
            }
            if (res1 != null) {
                res1.close();
            }
            if (res2 != null) {
                res2.close();
            }
        } catch (SQLException ex) {
            throw new RuntimeException(ex);
        }

        frame.setTitle("Admin Log");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(700, 520);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        JBBack.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frame.setContentPane(new AdminOperation(frame).JPMain);

            }
        });
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        JPMain = new JPanel();
        JPMain.setLayout(new BorderLayout(0, 0));
        JPTable = new JPanel();
        JPTable.setLayout(new BorderLayout(0, 0));
        JPMain.add(JPTable, BorderLayout.NORTH);
        JTableLog = new JTable();
        JTableLog.setBackground(new Color(-7086643));
        JTableLog.setForeground(new Color(-16777216));
        JPTable.add(JTableLog, BorderLayout.CENTER);
        JPButton2 = new JPanel();
        JPButton2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(20, 0, 0, 30), -1, -1));
        JPButton2.setBackground(new Color(-6828067));
        JPMain.add(JPButton2, BorderLayout.CENTER);
        JBBack = new JButton();
        JBBack.setText("Back");
        JPButton2.add(JBBack, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        JPButton2.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        JPButton2.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return JPMain;
    }

}